[package]
name = "holochain-kangaroo" # replace-me
version = "0.0.0" # replace-me -- Choose wisely, see "Note on Versioning" in README
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]

###### bump holochain dependencies here
holochain_client = { git = "https://github.com/holochain/holochain-client-rust", branch = "holochain-0.3.0-beta-dev.8" }
holochain = { version = "0.3.0-beta-dev.8", features = ["sqlite-encrypted"] }
holochain_types = "0.3.0-beta-dev.7"
holochain_zome_types = "0.3.0-beta-dev.6"
mr_bundle = "0.2.0"
######

either = "*"
futures = "0.3"
log = "0.4.14"
log4rs = "1.0.0"
opener = "0.5.0"
portpicker = "0.1.1"
semver = "1.0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sodoken = "0.0.9"
tauri = { version = "1.4", features = ["devtools", "dialog", "system-tray", "shell-open"] }
thiserror = "1"

# optional (single-instance):
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
